// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppugehameluiocnixbfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwdWdlaGFtZWx1aW9jbml4YmZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODA0ODMsImV4cCI6MjA1NzM1NjQ4M30.606dsfsX8vm7wYzMKLZkxvt01nwZzT5manFe3tAW2-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);